### ISSUE TITLE
Thunderbird 91 Add-on Options Toolbar entry missing after remove & reinstall ConfirmBeforeDelete

### ISSUE THREAD

**Issue by DLClark777** [caligraf/ConfirmBeforeDelete#10]
Without the confirmBeforeDelete Addon option I cannot disable folder lock.

**Comment by caligraf** [comment]
The options are available in Add-Ons manager tab, there is a new "wrench" button.
![image](https://user-images.githubusercontent.com/44136069/135677740-e883edf3-b3e1-4f44-8b7e-13f1b502c75b.png)
