### ISSUE TITLE
Not compatible with version 102.0

### ISSUE THREAD

**Issue by dimitris64bit** [caligraf/ConfirmBeforeDelete#12]
Please support. Thanks

**Comment by Giulioski** [comment]
Update to new TB version 102 is becoming very urgent. Is it possible to do it in the meantime changing some string valure in the extension?

**Comment by Giulioski** [comment]
I changed the manifest.json file and it's working again. I didn't checked every function if it's working or not but at least confirm before delete email message is working, and so it seems for other functions. Download it from here. it's only working for version 102.x, Future version 103 will not work !! it depends from the author... hope he can publish the official version
[www.centromedia.com/download/confirmbeforedelete@caligraf.xpi](url)

**Comment by dimitris64bit** [comment]
It prints this error when trying to delete a mail:
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIStringBundle.GetStringFromName]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://confirmbeforedelete/content/confirmbeforedelete/CBD-common.js :: CBD.confirmbeforedelete :: line 67"  data: no]

**Comment by dimitris64bit** [comment]
It just needed a restart. It works OK.

**Comment by caligraf** [comment]
new version is available for TB 115
