### ISSUE TITLE
Confirmation not working for me with "Shift-delete"

### ISSUE THREAD

**Issue by BillH99999** [caligraf/ConfirmBeforeDelete#15]
When I select Shift-Delete for a mesage in the Trash folder, I do not get a confirmation prompt as I do with Delete.

These are my settings:

![image1](https://github.com/caligraf/ConfirmBeforeDelete/assets/26846819/5f2c7e0b-838d-40b2-81f5-e3348ec5a0c0)

What am I doing wrong?

Thanks,
Bill

**Comment by caligraf** [comment]
I have created a new version 1.9.1 where I fixed not showed confirmation messages
Could you test if you still have the issue with the version 1.9.1 ?
https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.9.1/ConfirmBeforeDelete.xpi

**Comment by BillH99999** [comment]
That works.  Thanks!

Bill

**Comment by BillH99999** [comment]
I'm also having another problem when I use Shift-Delete.  The confirmation window is too small so the buttons are not visible.

![image1](https://github.com/caligraf/ConfirmBeforeDelete/assets/26846819/fc72fe18-cabe-452a-836c-3f713c0bc961)

Bill

**Comment by BillH99999** [comment]
> That seems to work for Shift-Delete. However, in my inbox, now when I delete a message (just Del not Shift-Del) I get the prompt and select that I want it to be deleted and the message gets deleted, but then goes back into my inbox.
> 
> Bill

I can confirm that confirmation is now working when I use Shift-Delete in the trash folder.

Bill

**Comment by BillH99999** [comment]
I'm also having another problem when I use Delete or Shift-Delete in the trash folder.  It also happens when I use Shift-Delete in any folder.  The window isn't large enough to hold the text and buttons.

![image1](https://github.com/caligraf/ConfirmBeforeDelete/assets/26846819/fc72fe18-cabe-452a-836c-3f713c0bc961)

Things are fine if I use just Delete in folders other than the trash folder.

![image](https://github.com/caligraf/ConfirmBeforeDelete/assets/26846819/9f0bb8d5-3b85-4664-881f-87a516fb9321)

Bill

**Comment by caligraf** [comment]
Do you have a theme installed ?

**Comment by BillH99999** [comment]
No... no theme installed.  

I've actually reverted to 1.8.1 at the mment as that seems to be working fine for me needs.  Even with 1.8.1 I am now getting a confirmation when I use Shift-Delete in the Trash folder.

**Comment by tomasz1986** [comment]
> I'm also having another problem when I use Delete or Shift-Delete in the trash folder. It also happens when I use Shift-Delete in any folder. The window isn't large enough to hold the text and buttons.
> 
> ![image1](https://user-images.githubusercontent.com/26846819/283663373-fc72fe18-cabe-452a-836c-3f713c0bc961.jpg)
> 
> Things are fine if I use just Delete in folders other than the trash folder.
> 
> ![image](https://user-images.githubusercontent.com/26846819/283664646-9f0bb8d5-3b85-4664-881f-87a516fb9321.png)
> 
> Bill

I can also confirm that the window pop-up is too small and requires manual resizing (Windows 10 x64, Thunderbird 115.4.3 with no custom themes). Also, is it just me that the new pop-up window doesn't respond to keyboard presses at all? What I mean is that I normally used the arrow and Enter keys to operate it, but now I'm forced to used the mouse.

**Comment by caligraf** [comment]
I have done a new version 1.9.2,
I have increased size of the window and I added handling of keyboard arrow keys:
https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.9.2/ConfirmBeforeDelete.xpi

**Comment by tomasz1986** [comment]
Thank you very much 🙂!

There is yet another problem which I forgot to mention last time. The pop-up window displays on a wrong monitor, e.g. here I've got two monitors - primary and secondary - and Thunderbird is open on the secondary monitor. However, the confirmation window seems to always show up on the primary screen.

**Comment by BillH99999** [comment]
> I have done a new version 1.9.2, I have increased size of the window and I added handling of keyboard arrow keys: https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.9.2/ConfirmBeforeDelete.xpi

I can confirm that the window size is now large enough.

Thanks caligraf!

Bill
