### ISSUE TITLE
Not compatible with TB 115

### ISSUE THREAD

**Issue by BillH99999** [caligraf/ConfirmBeforeDelete#16]
I just got updated to RB 115 and I see that this extension is not compatible.  Are you planning to update it to be compatible?

Thanks,
Bill

**Comment by Giulioski** [comment]
Is there any soul that can bring this plug-in back to life?

thank you

**Comment by Giulioski** [comment]
Is there a way to contact the author?

**Comment by BillH99999** [comment]
I have no idea if this email works or not, but...

The support email address shown at https://addons.thunderbird.net/en-US/thunderbird/addon/confirmbeforedelete/ 
 is olivier2042@outlook.fr.

Bill

**Comment by Giulioski** [comment]
Hi, thank you, I already wrote to this email last week but never got answer.

Giulio

**Comment by caligraf** [comment]
New version 1.8.0 compatible with YB 115 is available at https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.8.0/ConfirmBeforeDelete.xpi

**Comment by BillH99999** [comment]
@caligraf 

Thank you so much.  I'm really glad you were able to make it work for TB 115.  I installed it and it is working here.

Thanks,

Bill

**Comment by caligraf** [comment]
I published a new version 1.8.1 : https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.8.1/ConfirmBeforeDelete.xpi
I fixed two bugs:
Bug fix delete multiple messages with delete button in the thread Pane
Bug fix delete message with the button delete in the unified toolbar
