### ISSUE TITLE
ConfirmBeforeDelete not working with others tabs that the main one?

### ISSUE THREAD

**Issue by BackSpace54** [caligraf/ConfirmBeforeDelete#18]
Hi,
Can you confirm that ConfirmBeforeDelete doesn't work with tabs other than the main tab (i.e. it only works with the very first tab on the left)?
ConfirmBeforeDelete version 1.8.1
Thunderbird 115.2.3

Btw nice addon ;-)
Thanks, bye.

**Comment by caligraf** [comment]
I confirm it works only with the very first tab on the left

**Comment by caligraf** [comment]
I have created a new version 1.9.0 where I fixed not showed confirmation messages on new tabs or other windows
Could you test it ?
https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.9.0/ConfirmBeforeDelete.xpi

**Comment by BackSpace54** [comment]
Hi,
works on every tabs now, thanks.
