### ISSUE TITLE
Improved English messages

### ISSUE THREAD

**Issue by Duncan-Moore** [caligraf/ConfirmBeforeDelete#3]
I find the English wording of the configuration menu and delete confirmations somewhat quirky.
I've attached what I think is better for en-US.
This is relative to version 1.2.

[confirmbeforedelete.zip](https://github.com/caligraf/ConfirmBeforeDelete/files/3778591/confirmbeforedelete.zip)

**Comment by caligraf** [comment]
I have integrated your suggestions in version 1.4 and 1.5

**Comment by Duncan-Moore** [comment]
Thanks for doing that.

I can't find the ConfirmBeforeDelete options. 

They're not in the add-on description page, like other add-ons now have. And they're not on the Tools menu, where I think they used to be.

Does CBD still have configurable options?

I'm using Windows 10, TB 78.4.3 64-bit, CBD 1.5.2.

**Comment by caligraf** [comment]
Yes CBD is still have configurable options, it is in Tools > Add-On Preferences > ConfirmBeforeDelete.
Do you have it ?

**Comment by Duncan-Moore** [comment]
Found it. I was looking under Tools on the hamburger button, not Tools on the "Mail Toolbar"!

When deleting a folder from the trash, it's not asking for confirmation, even though I've checked all of the 'confirm' options in the settings.

**Comment by caligraf** [comment]
I have done a fix, you can test the new version 1.5.3 [https://github.com/caligraf/ConfirmBeforeDelete/releases/tag/1.5.3](https://github.com/caligraf/ConfirmBeforeDelete/releases/tag/1.5.3). It is not yet validated.

**Comment by Duncan-Moore** [comment]
Yes, that's working.

One other point I've noticed is that immediately after updating CBD, I get multiple confirmation boxes from CBD. I need to restart TB to get CBD working properly.

**Comment by caligraf** [comment]
in Thunderbird 68 add-ons were expected to be active after a restart, but now add-on can be activate at any time
I will check how i can fix this

**Comment by caligraf** [comment]
I have opened issue #7 for work on the issue above
