### ISSUE TITLE
No longer works with TB 78 :-(

### ISSUE THREAD

**Issue by softfoot** [caligraf/ConfirmBeforeDelete#6]
It's not flagged as incompatible.

I use it to protect folders and tagged messages but as of 78 it no longer protects them.

A very useful addon BTW.

Best regards,
Dave

**Comment by jh20001** [comment]
I do hope the plugin is lives on :)

**Comment by GaVenga** [comment]
Seems he (caligraf) is dead?! Fucking Corona?

**Comment by jh20001** [comment]
> Seems he (caligraf) is dead?! Fucking Corona?

A bit of a cruel thing to say

**Comment by caligraf** [comment]
I'm working on building a version compatible with TB 78

**Comment by jh20001** [comment]
woot!

**Comment by caligraf** [comment]
You can download a new version working on TB 78 at [https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.4/ConfirmBeforeDelete.xpi](https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.4/ConfirmBeforeDelete.xpi)
For the moment this version is not official, it is not yet validated.

**Comment by caligraf** [comment]
version 1.5.1 compatible with TB 78 is available [https://addons.thunderbird.net/fr/thunderbird/addon/confirmbeforedelete/](https://addons.thunderbird.net/fr/thunderbird/addon/confirmbeforedelete/)
@softfoot Can you confirm if it working for you ?

**Comment by jh20001** [comment]
Right on caligraf! Noticed when you send a folder to the trash, and then try to delete it, you have to confirm 3x times via popups before it will delete.

**Comment by caligraf** [comment]
@jh20001 I created version 1.5.2 to fix the issue [https://github.com/caligraf/ConfirmBeforeDelete/releases/tag/1.5.2](https://github.com/caligraf/ConfirmBeforeDelete/releases/tag/1.5.2)

**Comment by jh20001** [comment]
👍 
That fixed it! I'll let you know if I see any other anomalies :)

**Comment by caligraf** [comment]
I close this issue, if you find any bug please open a new issue
