### ISSUE TITLE
Doesn't work with Thunderbird 91.0 64-bit

### ISSUE THREAD

**Issue by igor-ws** [caligraf/ConfirmBeforeDelete#9]
Add-on installs just fine, but  prompt doesn't pop up when deleting a message.

I hope this great little add-on lives on.

**Comment by Giulioski** [comment]
UP
I confirm not working on 91.1.0

**Comment by caligraf** [comment]
I have fixed the compatibility issue with TB 91 in version 1.5.5.
The version 1.5.5 is not yet officially available, but you can download it here : https://github.com/caligraf/ConfirmBeforeDelete/releases/download/1.5.5/ConfirmBeforeDelete.xpi and install it manually.
